<a href="https://colab.research.google.com/github/kokilaammu/kokilaammu/blob/main/Copy_of_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [20]:
s = "Hi there Sam!"
string = "Hi there Sam!"
print(string.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [21]:
planet = "Earth"
diameter = 12742

print("The diameter of {} is {} kilometers.".format(planet, diameter))

#or, you can do it like that:

print(f"The diameter of {planet} is {diameter} kilometers.")

The diameter of Earth is 12742 kilometers.
The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [22]:
import numpy as np
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


# Numpy

In [23]:
import numpy as np
import numpy as np
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [24]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [26]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [30]:
import numpy as np
a = np.array([[1,2,],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [31]:
import pandas as pd
import pandas as pd
# Initialize data to lists. 

data = [{'a': 1, 'b': 2,}, 

        {'a': 10, 'b': 20,},
         
        {'a': 10, 'b': 20,}]

  
# Creates DataFrame. 

df = pd.DataFrame(data) 

  
# Print the data 
df

a   b
0   1   2
1  10  20
2  10  20

In [32]:
import pandas as pd
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [33]:
import pandas as pd 

  

per1 = pd.date_range(start ='01-01-2023',  

         end ='02-10-2023') 

  

for val in per1: 

    print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [36]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd  

import pandas as pd   

      
# List1   

lst = [['aaa', 22], ['bbb', 25],['ccc', 26]]  

  
# creating df object with columns specified     

print(df )

   calories  duration
0       420        50
1       380        40
2       390        45


In [35]:
import pandas as pd
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45
